# Generated by Django 4.2.12 on 2024-05-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergenreinfo',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='usergenreinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_actors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_movies',
        ),
        migrations.DeleteModel(
            name='UserActorInfo',
        ),
        migrations.DeleteModel(
            name='UserGenreInfo',
        ),
    ]
