# Generated by Django 4.2.12 on 2024-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("released_date", models.DateField(null=True)),
                ("popularity", models.FloatField(null=True)),
                ("vote_average", models.FloatField(null=True)),
                ("overview", models.TextField(null=True)),
                ("poster_path", models.CharField(max_length=200, null=True)),
                ("genres", models.ManyToManyField(to="movies.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("gender", models.IntegerField()),
                ("popularity", models.FloatField()),
                ("profile_path", models.CharField(max_length=200)),
                (
                    "movie",
                    models.ManyToManyField(
                        related_name="movie_actor", to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
