# Generated by Django 4.2.12 on 2024-05-21 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_actors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_moives', to=settings.AUTH_USER_MODEL),
        ),
    ]
